# -*- coding: utf-8 -*-
"""Assignment_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aWqhkVA1HUMnJ87bpk2QQB97yvcdjNul

# Basic Python

## 1. Split this string
"""

s = "Hi there Sam!"

s="Hi there Sam!"
s=s.split()
print(s);

"""## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.
"""

planet = "Earth"
diameter = 12742

planet = "Earth"
diameter = 12742
print( 'The diameter of {} is {} kilometers.' .format(planet,diameter));

"""## 3. In this nest dictionary grab the word "hello"
"""

d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

d = {
  'k1': [1, 2, 3, {
    'tricky': ['oh', 'man', 'inception', {
      'target': [1, 2, 3, 'hello']
    }]
  }]
}

"""# Numpy"""

import numpy as np

"""## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?
"""

import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)

import numpy as np
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

"""## 5. Create an array of all the even integers from 20 to 35"""

import numpy as np
array=np.arange(20,36)
print("Array of all the even integers from 20 to 35")
print(array)

"""## 6. Create a 3x3 matrix with values ranging from 0 to 8"""

import numpy as np
x =  np.arange(0,9).reshape(3,3)
print(x)

"""## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])
"""

a= np.array([1, 2, 3])
b= np.array([4, 5, 6])
np.concatenate((a, b))

"""# Pandas

## 8. Create a dataframe with 3 rows and 2 columns
"""

import pandas as pd

data = [['Meera',40],['Steve',70],['Elena',35]]
df = pd.DataFrame(data , columns=['Name', 'Age'])
df

"""## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023"""

p = pd.date_range(start ='1-1-2023' ,
                  end ='10-02-2023')
for val in p:
    print(val)

"""## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]
"""

lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

df = pd.DataFrame(lists, columns =['No','Name', 'Age'])
print(df)